fieldLayouts:
  67a5e26c-7faf-4467-b547-3f4e8e6b4569:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 58a2eed6-638c-4653-bda3-9e89571c88ff
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bd615216-7546-45dc-9fdd-2fbb8dca07c0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 32521f3e-9d40-45c9-a72b-3187f2cc02ac # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37c1e9b9-16bd-40c3-b2c0-cfacc110bc93
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 76008690-2923-4ac4-bb40-bd4b95b15d40 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45bdf6d7-4822-4c41-b74d-6eb82f4848ac
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 5c0ff787-6cf1-4be9-920e-70be481cc709
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c2783bdf-cb6f-4db5-849a-0569ca4d6894 # Team Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e697ac52-6218-48b1-87c2-db268d0aadaa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4c5cc5b-552c-40c3-b304-0819a9026dd7 # Team Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 467b3c7e-c137-4623-99d5-4512b16dce8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 06dc4121-2980-4adb-9a19-9eedb42098ed # Team Members
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8875abb-0b59-4797-9a00-ddddb4199a91
            userCondition: null
            warning: null
            width: 100
        name: Team
        uid: 4a1bd2cc-03aa-4f6d-b92d-d2ec1b697e16
        userCondition: null
handle: home
hasTitleField: false
name: Homepage
section: f01e8024-a0e4-4018-aa69-ae0c9d5ede2c # Homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
